{
 "title": "Consul",
 "tags": [ "system" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "_bucket", "label": "Bucket", "query": "15s,1m,10m,30m,1h,6h,12h,1d,7d" },
   {
    "name": "_environment",
    "label": "Environment",
    "query": "SHOW TAG VALUES WITH KEY = \"environment\""
   }
  ]
 },
 "panels": [
  {
   "title": "Consul Leader",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "expr": "consul_raft_leader_lastcontact_count",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "legendFormat": "{{host}}",
     "measurement": "raft_leader_lastContact",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "# servers in cluster",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 4, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "name",
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "os",
     "query": "SELECT derivative(sum(\"count\"), 1m) FROM \"memberlist_gossip\" WHERE \"environment\" =~ /^$_environment$/ AND \"service\" = 'consul' AND $timeFilter GROUP BY time($_bucket), \"$tag_host\"",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Consul leader transitions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Leader transition",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "environment" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "raft_state_leader",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "Leader election",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "raft_state_candidate",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "Consul host CPU (%)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent", "label": "CPU" }
   ],
   "targets": [
    {
     "alias": "$tag_host (System)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_system" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "consul", "operator": "=", "value": "server" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "$tag_host (User)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "consul", "operator": "=", "value": "server" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    },
    {
     "alias": "$tag_host (IOWait)",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_iowait" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "consul", "operator": "=", "value": "server" },
      { "condition": "AND", "key": "environment", "operator": "=~", "value": "/^$_environment$/" }
     ]
    }
   ]
  },
  {
   "title": "DNS response times (mean)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "dtdurationms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dns_domain_query",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "DNS Response times (90 percentile)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "dtdurationms", "label": "Time" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dns_domain_query",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "DNS Resolution (average)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" }
     ],
     "measurement": "dns_domain_query",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "DNS Resolution (90 percentile)",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "format": "dtdurationms",
   "valueName": "avg",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" }
     ],
     "measurement": "dns_domain_query",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "Number of DNS requests / $_bucket",
   "type": "table",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "dns_domain_query",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "Number of Go routines",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "runtime_num_goroutines",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "Bytes allocated",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "alias": "$tag_host",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "host" ], "type": "tag" }
     ],
     "measurement": "runtime_alloc_bytes",
     "query": "SELECT \"value\" FROM \"runtime_alloc_bytes\" WHERE \"environment\" =~ /^$_environment$/ AND \"service\" = 'consul' AND $timeFilter GROUP BY \"host\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "Suspected failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "environment" ], "type": "tag" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "memberlist_msg_suspect",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "Server writes",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" },
      { "params": [ "environment" ], "type": "tag" }
     ],
     "measurement": "raft_apply",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  },
  {
   "title": "Last contact between leader and followers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Mean",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" }
     ],
     "measurement": "raft_leader_lastContact",
     "select": [
      [
       { "params": [ "mean" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    },
    {
     "alias": "90%",
     "groupBy": [
      { "params": [ "$_bucket" ], "type": "time" }
     ],
     "measurement": "raft_leader_lastContact",
     "select": [
      [
       { "params": [ "90_percentile" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "environment", "operator": "=~", "value": "/^$_environment$/" },
      { "condition": "AND", "key": "service", "operator": "=", "value": "consul" }
     ]
    }
   ]
  }
 ]
}